[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
boring_onchain_queue = "E1mW9wpynHjwU3YhAHALh2x4sB2Jq8M3H5NgGYZnvUkg"
boring_vault_svm = "26YRHAHxMa569rQ73ifQDV9haF7Njcm3v7epVPvcpJsX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
test = "RUST_LOG=error yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
